site_name: AdvancedServerList Wiki
site_description: 'Wiki for the AdvancedServerList plugin'
site_author: 'Andre_601'
site_url: 'https://asl.andre601.ch'

copyright: |
  Images &copy; Andre_601<br>
  Docs licensed under <a href="https://codeberg.org/Andre601/AdvancedServerList/src/branch/master/LICENSE" target="_blank" rel="noopener noreferrer noopener">MIT</a>

docs_dir: docs/

repo_name: Andre601/AdvancedServerList
repo_url: https://codeberg.org/Andre601/AdvancedServerList

not_in_nav: |
  api/reference/structure.md

theme:
  name: 'material'
  custom_dir: 'docs/.overrides'
  favicon: 'assets/images/favicon.png'
  logo: 'assets/images/favicon.png'
  palette:
    scheme: 'slate'
    primary: 'indigo'
    accent: 'indigo'
  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - content.code.copy
  - content.tooltips

  icon:
    repo: 'simple/codeberg'
    admonition:
      note: 'octicons/pencil-24'
      abstract: 'octicons/checklist-24'
      info: 'octicons/info-24'
      tip: 'octicons/light-bulb-24'
      success: 'octicons/check-24'
      question: 'octicons/question-24'
      warning: 'octicons/alert-24'
      failure: 'octicons/x-circle-24'
      danger: 'octicons/zap-24'
      bug: 'octicons/bug-24'
      example: 'octicons/beaker-24'
      quote: 'octicons/quote-24'

extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/api-docs.css
  - assets/stylesheets/admo.css
  - assets/stylesheets/admonition.css

extra_javascript:
  - assets/js/repo-stats.js

extra:
  github_repository: !ENV [GITHUB_REPO_INSTANCE, False]
  social:
    - icon: 'simple/codeberg'
      link: 'https://codeberg.org/Andre601/AdvancedServerList'
    - icon: 'simple/modrinth'
      link: 'https://modrinth.com/plugin/advancedserverlist'
    - icon: 'fontawesome/solid/paper-plane'
      link: 'https://hangar.papermc.io/Andre_601/AdvancedServerList'

plugins:
  - search
  - glightbox
  - pagenav-generator

markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.superfences:
  - pymdownx.snippets:
      base_path: docs/.snippets
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.details:

hooks:
  - docs/.hooks/badges.py
  - docs/.hooks/replacer.py

nav:
  - Home: index.md
  - Getting Started: getting-started/index.md
  - Commands: commands/index.md
  - Profiles:
    - profiles/index.md
    - Expressions: profiles/expressions.md
    - Formatting: profiles/formatting.md
    - Placeholders: profiles/placeholders.md
  - Examples: examples/index.md
  - Migration:
    - migration/index.md
    - v3.8.0 to v3.9.0: migration/v3_8_0-to-v3_9_0.md
    - v3.7.0 to v3.8.0: migration/v3_7_0-to-v3_8_0.md
    - '< v3.7.0 to v3.7.0': migration/pre-v3_7_0-to-v3_7_0.md
    - v1.9.0 to v1.10.0: migration/v1_9_0-to-v1_10_0.md
    - v1.5.3 to v1.6.0: migration/v1_5_3-to-v1_6_0.md
  - API:
    - api/index.md
    - Changelog: api/changelog.md
    - Javadocs: api/javadocs.md
    - Source Code: api/source.md
    - Reference:
      - api/reference/index.md
      - api:
        - api/reference/api/index.md
        - ch.andre601.advancedserverlist.api:
          - api/reference/api/ch.andre601.advancedserverlist.api/advancedserverlistapi.md
          - api/reference/api/ch.andre601.advancedserverlist.api/placeholderprovider.md
          - events:
            - api/reference/api/ch.andre601.advancedserverlist.api/events/genericserverlistevent.md
          - exceptions:
            - api/reference/api/ch.andre601.advancedserverlist.api/exceptions/invalidplaceholderproviderexception.md
          - objects:
            - api/reference/api/ch.andre601.advancedserverlist.api/objects/genericplayer.md
            - api/reference/api/ch.andre601.advancedserverlist.api/objects/genericserver.md
            - api/reference/api/ch.andre601.advancedserverlist.api/objects/nullbool.md
          - profiles:
            - '<api__record></api__record> ProfileEntry':
              - api/reference/api/ch.andre601.advancedserverlist.api/profiles/profileentry/index.md
              - api/reference/api/ch.andre601.advancedserverlist.api/profiles/profileentry/builder.md
      - platform-bukkit:
        - api/reference/platform-bukkit/index.md
        - ch.andre601.advancedserverlist.api.bukkit:
          - events:
            - api/reference/platform-bukkit/ch.andre601.advancedserverlist.api.bukkit/events/preserverlistsetevent.md
          - objects:
            - api/reference/platform-bukkit/ch.andre601.advancedserverlist.api.bukkit/objects/bukkitplayer.md
            - api/reference/platform-bukkit/ch.andre601.advancedserverlist.api.bukkit/objects/bukkitserver.md
      - platform-bungeecord:
        - api/reference/platform-bungeecord/index.md
        - ch.andre601.advancedserverlist.api.bungeecord:
          - events:
            - api/reference/platform-bungeecord/ch.andre601.advancedserverlist.api.bungeecord/events/preserverlistsetevent.md
          - objects:
            - api/reference/platform-bungeecord/ch.andre601.advancedserverlist.api.bungeecord/objects/bungeeplayer.md
            - api/reference/platform-bungeecord/ch.andre601.advancedserverlist.api.bungeecord/objects/bungeeproxy.md
      - platform-velocity:
        - api/reference/platform-velocity/index.md
        - ch.andre601.advancedserverlist.api.velocity:
          - events:
            - api/reference/platform-velocity/ch.andre601.advancedserverlist.api.velocity/events/preserverlistsetevent.md
          - objects:
            - api/reference/platform-velocity/ch.andre601.advancedserverlist.api.velocity/objects/velocityplayer.md
            - api/reference/platform-velocity/ch.andre601.advancedserverlist.api.velocity/objects/velocityproxy.md
  - Addons:
    - addons/index.md
    - BanPlugins: addons/banplugins.md
  - PlaceholderAPI: placeholderapi/index.md