site_name: AdvancedServerList Wiki
site_description: 'Wiki for the AdvancedServerList plugin'
site_author: 'Andre_601'
site_url: 'https://docs.andre601.ch/AdvancedServerList'

copyright: |
  &copy; Andre_601

docs_dir: docs/

repo_name: Andre601/AdvancedServerList
repo_url: https://github.com/Andre601/AdvancedServerList

nav:
  - Home:
    - index.md
    - Commands: commands.md
  - Profiles:
    - profiles/index.md
    - Formatting: profiles/formatting.md
    - Placeholders: profiles/placeholders.md
  - API:
    - api/index.md
    - Changelog: api/changelog.md
  - Migration:
    - migration/index.md
    - 'v1.5.3 to v1.6.0': migration/v1_5_3-to-v1_6_0.md
    - 'v1.9.0 to v1.10.0': migration/v1_9_0-to-v1_10_0.md
  - Examples: examples/index.md
  - PlaceholderAPI: placeholderapi/index.md

theme:
  name: 'material'
  favicon: 'assets/images/favicon.png'
  logo: 'assets/images/favicon.png'
  palette:
    scheme: 'slate'
    primary: 'indigo'
    accent: 'indigo'
  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - content.code.copy

  icon:
    repo: 'octicons/mark-github-16'
    admonition:
      note: 'octicons/tag-24'
      abstract: 'octicons/checklist-24'
      info: 'octicons/info-24'
      tip: 'octicons/squirrel-24'
      success: 'octicons/check-24'
      question: 'octicons/question-24'
      warning: 'octicons/alert-24'
      failure: 'octicons/x-circle-24'
      danger: 'octicons/zap-24'
      bug: 'octicons/bug-24'
      example: 'octicons/beaker-24'
      quote: 'octicons/quote-24'

extra_css:
  - assets/stylesheets/custom.css

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Andre601/asl-wiki'
  version:
    provider: 'mike'
    default:
      - latest
      - dev

plugins:
  - search
  - glightbox

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details:
