site_name: AdvancedServerList Wiki
site_description: 'Wiki for the AdvancedServerList plugin'
site_author: 'Andre_601'
site_url: 'https://asl.andre601.ch'

copyright: |
  Images &copy; Andre_601<br>
  Docs licensed under <a href="https://codeberg.org/Andre601/AdvancedServerList/src/branch/master/LICENSE" target="_blank" rel="noopener noreferrer noopener">MIT</a>

docs_dir: docs/

repo_name: Andre601/AdvancedServerList
repo_url: https://codeberg.org/Andre601/AdvancedServerList

not_in_nav: |
  api/reference/structure.md

theme:
  name: 'material'
  custom_dir: 'docs/.overrides'
  favicon: 'assets/images/favicon.png'
  logo: 'assets/images/favicon.png'
  palette:
    scheme: 'slate'
    primary: 'indigo'
    accent: 'indigo'
  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - content.code.copy
  - content.tooltips

  icon:
    repo: 'simple/codeberg'
    admonition:
      note: 'octicons/pencil-24'
      abstract: 'octicons/checklist-24'
      info: 'octicons/info-24'
      tip: 'octicons/light-bulb-24'
      success: 'octicons/check-24'
      question: 'octicons/question-24'
      warning: 'octicons/alert-24'
      failure: 'octicons/x-circle-24'
      danger: 'octicons/zap-24'
      bug: 'octicons/bug-24'
      example: 'octicons/beaker-24'
      quote: 'octicons/quote-24'

extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/api-docs.css
  - assets/stylesheets/admo.css

extra_javascript:
  - assets/js/repo-stats.js

extra:
  github_repository: !ENV [GITHUB_REPO_INSTANCE, False]
  social:
    - icon: 'simple/codeberg'
      link: 'https://codeberg.org/Andre601/AdvancedServerList'
    - icon: 'simple/modrinth'
      link: 'https://modrinth.com/plugin/advancedserverlist'
    - icon: 'fontawesome/solid/paper-plane'
      link: 'https://hangar.papermc.io/Andre_601/AdvancedServerList'

plugins:
  - search
  - glightbox
  - awesome-pages:
      filename: .pages.yml
  - pagenav-generator

markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.superfences:
  - pymdownx.snippets:
      base_path: docs/.snippets
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.details:

hooks:
  - docs/.hooks/badges.py
  - docs/.hooks/replacer.py