#
# Set the priority of this profile.
# Higher number = Higher priority.
#
# Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#priority
#
priority: 0

#
# Set conditions that needs to be met.
# Only when all conditions return true will the profile be shown (Given no profile with higher priority is used).
#
# Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#conditions
#
#conditions:
#  - '{playerVersion} < 759'

#
# Option that allows you to define multiple profiles to use.
# Each entry supports the same options as the server list profile does. Whenever an option is not present, or set to
# an empty value (If supported) would the option in the file be used (if present).
# This allows you to f.e. randomize the MOTD while keeping other options the same, without copy-pasting the same options.
#
# A profile will be selected randomly.
#
# Remove this option or set it to profiles: [] to use the global options of this file.
#
# Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#profiles
#
#profiles:
#  - motd:
#      - '<aqua>Line 1'
#      - '<aqua>Line 2'
#    favicon: ''
#    playerCount:
#      hidePlayers: false
#      hover:
#        - '<green>Line 1'
#        - '<green>Line 2'
#        - '<green>Line 3'
#      text: ''
#      extraPlayers:
#        enabled: false
#        amount: 0

#
# Set the default (Global) MOTD used by this server list profile.
# Supports HEX colors for 1.16+ servers including gradients using MiniMessage's <gradient:color:color> format.
# 
# Remove this option or set it to motd: [] to not alter the MOTD.
#
# Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#motds
#
motd:
  - '<grey>Line 1'
  - '<grey>Line 2'

#
# Allows you to set a global (Default) favicon for this server list profile.
# You can use one of three possible options:
#   1. A file name matching a PNG file located in the 'favicons' folder (Needs to end with .png)
#   2. A URL pointing to a valid Image
#   3. ${player name} to display the player's head as favicon. Uses https://mc-heads.net for this
#
# Remove this option or set to favicon: '' to not replace the Favicon.
#
# Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#favicon
#
favicon: ''

#
# Contains various options to manipulate the player count (Text displaying online and max players allowed).
#
# Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#playercount
#
playerCount:
  #
  # Whether AdvancedServerList should hide the player count or not.
  # When set to true will the player count display '???' instead of <online>/<max>
  #
  # Note that when this is enabled will all other options, except for 'extraPlayers', be ignored.
  #
  # Defaults to false when not present.
  #
  # Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#hideplayers
  #
  hidePlayers: false
  #
  # Sets the text displayed when hovering over the player count.
  #
  # Remove this option or set it to hover: [] to not modify the player samples on the player count.
  #
  # Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#hover
  #
  hover:
    - '<grey>Line 1'
    - '<grey>Line 2'
    - '<grey>Line 3'
  #
  # Modifies the text that usually displays '<online>/<max>'
  # 
  # Note that when used, the Ping icon will display as 'outdated server'/'outdated client'.
  # This is nothing that can be fixed or avoided and would require changes from Mojang.
  #
  # Remove this option or set it to text: '' to not modify the player count text.
  #
  # Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#text
  #
  text: ''
  #
  # Allows you to modify the max player count displayed.
  # Note that this will affect ${server playersMax} (Except for when used in conditions).
  #
  # Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#extraPlayers
  #
  extraPlayers:
    #
    # Enables/Disables the extraPlayers option.
    # When enabled will the total amount of players allowed be modified to the current
    # number of online players + 'amount'
    #
    # Defaults to false when not present.
    #
    # Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#enabled
    #
    enabled: false
    #
    # Sets how much should be added/subtracted from the current number of online players
    # to then use for the max player count.
    #
    # Example:
    # When set to 1 while 10 players are online would the player count - if unmodified -
    # display '10/11'. When -1 is used will it display '10/9'
    #
    # Defaults to 0 when not present.
    #
    # Read more: https://github.com/Andre601/AdvancedServerList/wiki/Profiles#amount
    #
    amount: 0