name: 'ASLAdvancedBanAddon'
author: 'Andre_601'
version: '${plugin.version}'
description: '${plugin.description}'

main: 'ch.andre601.advancedserverlist.banplugins.paper.AdvancedBanPlaceholders'

api-version: '1.19'

dependencies: 
  server: 
    AdvancedServerList:
      required: false
      load: BEFORE
    AdvancedBans:
      required: false
      load: BEFORE