when:
  event: tag

depends_on:
  - publish_assets

steps:
  createFiles:
    secrets:
      - cb_token
      - gh_token
    commands:
      # Obrain Prerelease status
      - |-
        export PRERELEASE=`curl --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases?limit=10" \
        --header 'Authorization: token $CB_TOKEN' \
        --header 'Accept: application/json' -s -S \
        --fail-with-body | jq -r ".[] | select (.tag_name==\"$CI_COMMIT_TAG\").prerelease"`
      # Obtain Release changelog
      - |-
        export RELEASE_CHANGELOG=`curl --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases?limit=10" \
        --header 'Authorization: token $CB_TOKEN' \
        --header 'Accept: application/json' -s -S \
        --fail-with-body | jq -r ".[] | select (.tag_name==\"$CI_COMMIT_TAG\").body"`
      # Create a new release on GitHub
      - |-
        curl --location \
        -X POST \
        --header "Accept: application/vnd.github+json" \
        --header "Authorization: Bearer $GH_TOKEN" \
        --header "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/Andre601/AdvancedServerList/releases \
        -d '{"tag_name":"${CI_COMMIT_TAG}","target_commitish":"master","name":"${CI_COMMIT_TAG}","body":"> *Automated release from [Codeberg Repository](https://codeberg.org/Andre601/AdvancedServerList/releases/tag/${CI_COMMIT_TAG})*\n\n${RELEASE_CHANGELOG}","draft":false,"prerelease":$PRERELEASE,"generate_release_notes":false}'