when:
  - event: pull_request
    path:
      include: ['.woodpecker/pr_preview.yml', 'requirements.txt', 'mkdocs.yml', 'docs/**']

variables:
  setup_git: &setup_git
    - apk add git
    - git config --global user.email "andre@andre601.ch"
    - git config --global user.name "ASL Docs Builder"

steps:
  cloneTargetRepo:
    image: alpine:3.18.4
    commands:
      - chmod -R a+w .
      - <<: *setup_git
      - git clone https://codeberg.org/Andre601/asl-docs.git site
      - chmod -R a+w site
      - cd site
      - git switch pr-${CI_COMMIT_PULL_REQUEST} 2>/dev/null || git switch -c pr-${CI_COMMIT_PULL_REQUEST}
  buildDocs:
    image: woodpeckerci/plugin-mkdocs:latest
    settings:
      pip_install_file: requirements.txt
  commitAndPush:
    image: alpine:3.18.4
    secrets:
      - bot_token
    commands:
      - <<: *setup_git
      - mv domains site/.domains
      - cd site
      - git remote add upstream https://$BOT_TOKEN@codeberg.org/Andre601/asl-docs.git
      - git add --all
      - git commit -m "Update Preview for PR ${CI_COMMIT_PULL_REQUEST} ($( env TZ=Europe/Zurich date +"%d.%m.%Y %Z" )) [SKIP CI]"
      - git push --set-upstream upstream pr-${CI_COMMIT_PULL_REQUEST} -f
  commentOnSuccess:
    image: mcs94/gitea-comment
    when:
      - status: ['success']
    secrets:
      - bot_token
    settings:
      gitea_address: https://codeberg.org
      gitea_token:
        from_secret: BOT_TOKEN
      comment: |-
        Pull request Preview ready!

        | Name   | Value                                                 |
        |--------|-------------------------------------------------------|
        | Commit | ${CI_COMMIT_SHA}                                      |
        | Link   | https://asl.andre601.ch/@pr-${CI_COMMIT_PULL_REQUEST} |
  commentOnFailure:
    image: mcs94/gitea-comment
    when:
      - status: ['failure']
    secrets:
      - bot_token
    settings:
      gitea_address: https://codeberg.org
      gitea_token:
        from_secret: BOT_TOKEN
      comment: |-
        Issue while creating Pull request preview.
        Please check the CI logs for any reasons: ${CI_PIPELINE_URL}