when:
  - event: pull_request
    evaluate: 'CI_COMMIT_TARGET_BRANCH == "master"'
    path:
      include: ['.woodpecker/publish_docs.yml', 'requirements.txt', 'mkdocs.yml', 'docs/**']

variables:
  setup_git: &setup_git
    - apk add git
    - git config --global user.email "andre@andre601.ch"
    - git config --global user.name "ASL Docs Builder"

steps:
  cloneTargetRepo:
    image: alpine:3.18.4
    commands:
      - chmod -R a+w .
      - <<: *setup_git
      - git clone https://codeberg.org/Andre601/asl-docs.git site
      - chmod -R a+w site
      - cd site
      - git switch pr-${CI_COMMIT_PULL_REQUEST} 2>/dev/null || git switch -c ${CI_COMMIT_PULL_REQUEST}
  buildDocs:
    image: woodpeckerci/plugin-mkdocs:latest
    settings:
      pip_install_file: requirements.txt
  commitAndPush:
    image: alpine:3.18.4
    secrets:
      - bot_token
    commands:
      - <<: *setup_git
      - mv domains site/.domains
      - cd site
      - git remote add origin https://$BOT_TOKEN@codeberg.org/Andre601/asl-docs.git
      - git remote set-branches pr-${CI_COMMIT_PULL_REQUEST}
      - git add --all
      - git commit -m "Update AdvancedServerList Docs ($( env TZ=Europe/Zurich date +"%d.%m.%Y %Z" )) [SKIP CI]"
      - git push --set-upstream origin pr-${CI_COMMIT_PULL_REQUEST} -f
  writeComment:
    image: mcs94/gitea-comment
    secrets:
      - bot_token
    settings:
      gitea_address: https://codeberg.org
      gitea_token:
        from_secret: BOT_TOKEN
      comment: >
        Build-preview created!

        | Name   | Value                                                 |
        |--------|-------------------------------------------------------|
        | Commit | ${CI_COMMIT_SHA}                                      |
        | Link   | https://asl.andre601.ch/@pr-${CI_COMMIT_PULL_REQUEST} |