when:
  - event: tag
    branch: master

steps:
  createFiles:
    image: maven:3.9.6-eclipse-temurin-17
    secrets:
      - source: cb_token
        target: codeberg_api_token
      - source: modrinth_api_token
        target: modrinth_api_token
      - source: hangar_api_token
        target: hangar_api_token
      - source: discord_webhook_url
        target: discord_webhook_url
    commands:
      # Create the jar files.
      - mvn clean install
      # Move VersionUploader jar file
      - cd version-uploader/target/
      - mv VersionUploader.jar ../../
      - cd ../../
      # Execute Jar file
      - java -jar VersionUploader.jar --all
  uploadToCodeberg:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      files:
        - "bungeecord/target/AdvancedServerList-*.jar"
        - "paper/target/AdvancedServerList-*.jar"
        - "velocity/target/AdvancedServerList-*.jar"
        - "addons/banplugins/target/AdvancedServerList-*.jar"
      api_key:
        from_secret: CB_TOKEN
  postOnMastodon:
    image: woodpeckerci/plugin-mastodon-post
    when:
      - status: ['success']
    settings:
      server_url: https://blobfox.coffee
      access_token:
        from_secret: MASTODON_TOKEN
      status: '${CI_COMMIT_TAG} of #AdvancedServerList has been released and can be found on Modrinth (https://modrinth.com/plugin/AdvancedServerList), Hangar (https://hangar.papermc.io/Andre_601/AdvancedServerList) and Codeberg (https://codeberg.org/Andre601/AdvancedServerList).'
      visibility: public