when:
  event: tag

depends_on:
  - sync_mirror

matrix:
  include:
    - PLATFORM: Bukkit
      DIRECTORY: bukkit
    - PLATFORM: BungeeCord
      DIRECTORY: bungeecord
    - PLATFORM: Velocity
      DIRECTORY: velocity

steps:
  buildFiles:
    image: eclipse-temurin
    secrets:
      - cb_token
    commands:
      # Create the jar files.
      - mvn clean install
      # Get Release ID for upload
      - |-
        export RELEASE_ID=`curl --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases?limit=10" \
        --header 'Authorization: token $CB_TOKEN' \
        --header 'Accept: application/json' -s -S \
        --fail-with-body | jq -r ".[] | select (.tag_name==\"$CI_COMMIT_TAG\").id")`
  uploadFiles:
    image: eclipse-temurin
    secrets:
      - cb_token
    commands:
      # Upload release assets to Codeberg release
      - |-
        curl --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases/$RELEASE_ID/assets" \
        --header "Authorization: token $CB_TOKEN" \
        --header "Content-Type: multipart/form-data" -s -S \
        --form "attachment=@${DIRECTORY}/target/AdvancedServerList-${PLATFORM}-${CI_COMMIT_TAG##v}.jar;type=application/octet-stream" \
        --fail-with-body