when:
  - event: tag
    branch: master

steps:
  createFiles:
    image: maven:3.9.4-eclipse-temurin-17
    secrets:
      - source: cb_token
        target: codeberg_api_token
      - source: gh_token
        target: github_api_token
      - modrinth_api_token
      - hangar_api_token
    commands:
      # Create the jar files.
      - mvn clean install
      # Move VersionUploader jar file
      - cd version-uploader/target/
      - mv VersionUploader.jar ../../
      - cd ../../
      # Execute Jar file
      - java -jar VersionUploader.jar --all