when:
  - event: tag
    branch: master

steps:
  createFiles:
    image: maven:3.9.4-eclipse-temurin-17
    commands:
      # Create the jar files.
      - mvn clean install
  #uploadFiles:
  #  image: badouralix/curl-jq
  #  secrets:
  #    - cb_token
  #  commands:
  #    # Get release info and setup env vars.
  #    - |-
  #      export JSON=`curl --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases?limit=10" \
  #      --header 'Authorization: token $CB_TOKEN' \
  #      --header 'Accept: application/json' -s -S \
  #      --fail-with-body | jq ".[] | select (.tag_name==\"$CI_COMMIT_TAG\") | ."`
  #    - export PLUGIN_CHANGELOG=$( echo $JSON | jq -r '.body' )
  #    - export PLUGIN_PRE_RELEASE=$( echo $JSON | jq -r '.prerelease' )
  #    - export RELEASE_ID=$( echo $JSON | jq -r '.id' )
  #    # Upload release assets to Codeberg release
  #    - |-
  #      curl -X POST --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases/$RELEASE_ID/assets" \
  #      --header "Authorization: token $CB_TOKEN" \
  #      --header "Content-Type: multipart/form-data" -s -S \
  #      --form "attachment=@bukkit/target/AdvancedServerList-Bukkit-${CI_COMMIT_TAG##v}.jar;type=application/octet-stream" \
  #      --fail-with-body
  #    - |-
  #      curl -X POST --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases/$RELEASE_ID/assets" \
  #      --header "Authorization: token $CB_TOKEN" \
  #      --header "Content-Type: multipart/form-data" -s -S \
  #      --form "attachment=@bungeecord/target/AdvancedServerList-BungeeCord-${CI_COMMIT_TAG##v}.jar;type=application/octet-stream" \
  #      --fail-with-body
  #    - |-
  #      curl -X POST --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases/$RELEASE_ID/assets" \
  #      --header "Authorization: token $CB_TOKEN" \
  #      --header "Content-Type: multipart/form-data" -s -S \
  #      --form "attachment=@velocity/target/AdvancedServerList-Velocity-${CI_COMMIT_TAG##v}.jar;type=application/octet-stream" \
  #      --fail-with-body
  uploadToModrinthAndMaven:
    image: eclipse-temurin
    secrets:
      - cb_token
      - modrinth_api_token
      - hangar_api_token
    commands:
      # Move VersionUploader.jar
      - cd version-uploader/target/
      - mv VersionUploader.jar ../../
      - cd ../../
      # Create Modrinth releases
      - java -jar VersionUploader.jar --modrinth
      # Create Hangar release
      - java -jar VersionUploader.jar --hangar