when:
  - branch: '${CI_REPO_DEFAULT_BRANCH}'
    event: push
    path:
      include: ['.woodpecker/publish_docs.yml', 'requirements.txt', 'mkdocs.yml', 'docs/**']

variables:
  setup_git: &setup_git
    - apk add git
    - git config --global user.email "github@andre601.ch"
    - git config --global user.name "ASL Docs Builder"

steps:
  cloneTargetRepo:
    image: alpine:3.18.4
    commands:
      - chmod -R a+w .
      - <<: *setup_git
      - git clone -b pages https://codeberg.org/Andre601/asl-docs site
      - chmod -R a+w site
  buildDocs:
    image: woodpeckerci/plugin-mkdocs:latest
    settings:
      pip_install_file: requirements.txt
  commitAndPush:
    image: alpine:3.18.4
    secrets:
      - cb_token
    commands:
      - <<: *setup_git
      - mv domains site/.domains
      - cd site
      - git remote set-url origin https://$CB_TOKEN@codeberg.org/Andre601/AdvancedServerList.git
      - git add --all
      - git commit -m "Update AdvancedServerList Docs ($( env TZ=Europe/Zurich date +"%d.%m.%Y %Z" )) [SKIP CI]"
      - git push