platform: linux/amd64

when:
  event:
    - cron
    - push
    - manual

steps:
  renovateDryRun:
    image: renovate/renovate
    pull: true
    commands:
      - chmod -R a+w .
      - git config --global user.email "github@andre601.ch"
      - git config --global user.name "Andre601_Renovate_Bot"
      - renovate $${CI_REPO}
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://codeberg.org
      LOG_LEVEL: debug
      RENOVATE_DRY_RUN: full
    secrets:
      - source: rb_token
        target: renovate_token
    when:
      - event: push
  renovate:
    image: renovate/renovate
    pull: true
    commands:
      - chmod -R a+w .
      - git config --global user.email "github@andre601.ch"
      - git config --global user.name "Andre601_Renovate_Bot"
      - renovate $${CI_REPO}
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://codeberg.org
      LOG_LEVEL: debug
    secrets:
      - source: rb_token
        target: renovate_token
    when:
      - event: cron
        cron: renovate
      - event: manual