when:
  - event: push
    branch: master
  - event: tag

steps:
  pushToMirror:
    secrets:
      - gh_token
    commands:
      - chmod -R a+w
      # Configure Git
      - git config --global --add safe.directory /woodpecker/src/codeberg.org/Andre601/AdvancedServerList
      - git config --global user.email "github@andre601.ch"
      - git config --global user.name "Git Sync"
      - git config --global init.defaultBranch master
      # Clone GitHub repository
      - git remote add gh-upstream https://$GH_TOKEN@github.com/Andre601/AdvancedServerList
      - git push gh-upstream --force