when:
  - event: push

steps:
  testing:
    image: badouralix/curl-jq
    secrets:
      - cb_token
    commands:
      - echo $TAG
      - |-
        export JSON=$( curl "https://codeberg.org/api/v1/user" \
        --header "Authorization: token $CB_TOKEN" \
        --header "Accept: application/json" -s -S \
        --fail-with-body )
      - echo $JSON