when:
  - event: push

steps:
  testing:
    image: badouralix/curl-jq
    secrets:
      - cb_token
    environment:
      TAG: v3.4.0
    commands:
      - |-
        export JSON=$( curl "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases?limit=10" \
        --anyauth
        --header 'Authorization: token $CB_TOKEN' \
        --header 'Accept: application/json' -s -S \
        --fail-with-body | jq ".[] | select (.tag_name==\"$TAG\")." )
      - echo $JSON
      - export PLUGIN_CHANGELOG=$( echo $JSON | jq -r '.body' )
      - echo $PLUGIN_CHANGELOG
      - export PLUGIN_PRERELEASE=$( echo $JSON | jq -r '.prerelease' )
      - echo $PLUGIN_PRERELEASE
      - export RELEASE_ID=$( echo $JSON | jq -r '.id' )
      - echo $RELEASE_ID