when:
  - event: push

steps:
  testing:
    image: badouralix/curl-jq
    secrets:
      - cb_token
    environment:
      PLUGIN_CHANGELOG: Lorem Ipsum dolo"r sit a'med
      TAG: v3.4.0
      PLUGIN_PRERELEASE: 'false'
    commands:
      - echo $TAG
      - |-
        json=$( jq -n -c \
        --arg tag_name "$TAG" \
        --arg name "$TAG" \
        --arg target_commitish "master" \
        --arg body "$PLUGIN_CHANGELOG" \
        --arg draft false \
        --arg prerelease $PLUGIN_PRERELEASE \
        '{"tag_name":"$tag_name","name":"$name","target_commitish":"$target_commitish","body":"$body","draft":$draft,"prerelease":$prerelease}' )
      - echo $JSON