#
# Big thank you to @Kir-Antipov for providing this workflow file.
# Check out his mc-publish action here: https://github.com/Kir-Antipov/mc-publish
#

name: Publish Assets

on:
  workflow_dispatch:

jobs:
  buildJars:
    runs-on: ubuntu-latest
    outputs:
      plugin_release: ${{ steps.github-release.outputs.PLUGIN_RELEASE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get Version from Release
        id: github-release
        run: |
          version=$(echo ${{ github.event.release.tag_name }} | cut -d'v' -f2)
          echo "PLUGIN_RELEASE=$version" >> $GITHUB_OUTPUT
      - name: Set up JDK 1.16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'maven'
      - name: Build Jar files
        run: mvn clean install
      - name: Save All files
        uses: actions/upload-artifact@v3
        with:
          name: asl-files
          path: |
            */target/AdvancedServerList-*.jar
            hangar-uploader/target/HangarUploader.jar
          if-no-files-found: error
          retention-days: 1
  publish:
    needs: [buildJars]
    strategy:
      matrix:
        include:
          - platforms: BungeeCord, Waterfall
            directory: bungeecord
            loaders: |
              bungeecord
              waterfall
          - platforms: Spigot, Paper
            directory: bukkit
            loaders: |
              spigot
              paper
          - platforms: Velocity
            directory: velocity
            loaders: velocity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Jar files
        uses: actions/download-artifact@v3
        with:
          name: asl-files
          path: ${{ matrix.directory }}/target
      - name: Show folder structure
        run: ls -R
      