name: 'Deploy Site (Push)'

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'mkdocs-theme/**'
      - 'requirements.txt'
    branches:
      - master
    tags-ignore:
      - '**'

env:
  GITHUB_REPO_INSTANCE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Create/Get Cache
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
      - name: Deploy Files
        run: mkdocs gh-deploy --force
