name: Hangar Release Upload

on:
  workflow_dispatch:
    inputs:
     version:
       description: "The plugin version"
       required: true
       type: string
  #release:
  #  types:
  #    - published

jobs:
  buildJars:
    runs-on: ubuntu-latest
    name: 'Build Jar files'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 16
          cache: 'maven'
      - name: Build Jars
        run: mvn --projects :core,:bukkit,:bungeecord,:velocity,:hangar-uploader clean install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: asl-files
          path: |
            */target/AdvancedServerList-*.jar
            hangar-uploader/target/HangarUploader.jar
  listJars:
    needs: [buildJars]
    runs-on: ubuntu-latest
    name: 'List Jar files'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: asl-files
      - name: List Folder structure
        run: ls -R
    
