#
# Big thank you to @Kir-Antipov for providing this workflow file.
# Check out his mc-publish action here: https://github.com/Kir-Antipov/mc-publish
#

name: Publish Assets

on:
  release:
    types: [published]

jobs:
  buildJars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Load Maven Cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build Jar files
      run: mvn clean install
    - name: Save Jar files
      uses: actions/cache@v3
      with:
        key: ${{ github.event.release.tag_name }}-asl-cache
        path: |
          bungeecord/target/AdvancedServerList-*.jar
          paper/target/AdvancedServerList-*.jar
          spigot/target/AdvancedServerList-*.jar
          velocity/target/AdvancedServerList-*.jar
  publish:
    needs: [buildJars]
    strategy:
      matrix:
        include:
          - loaders: |
              bungeecord
              waterfall
            directory: bungeecord
            name: BungeeCord, Waterfall
          - loaders: paper
            directory: paper
            name: Paper
          - loaders: spigot
            directory: spigot
            name: Spigot
          - loaders: velocity
            directory: velocity
            name: Velocity
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Jar files
      uses: actions/cache@v3
      with:
        key: ${{ github.event.release.tag_name }}-asl-cache
        path: ${{ matrix.directory }}/target/AdvancedServerList-*.jar
    - name: Obtain GitHub Release version
      id: github-release
      run: |
        version=$(echo ${{ github.event.release.tag_name }} | cut -d'v' -f2)
        echo "::set-output name=version::$version"
    - name: Upload AdvancedServerList (${{ matrix.name }}) to GitHub and Modrinth
      uses: Kir-Antipov/mc-publish@v3.2
      with:
        name: v${{ steps.github-release.outputs.version }} - ${{ matrix.name }}
        version: ${{ steps.github-release.outputs.version }}
        version-type: release
        files: ${{ matrix.directory}}/target/AdvancedServerList-*.jar
        files-secondary: ""
        loaders: ${{ matrix.loaders }}
        version-resolver: releases
        game-versions: '1.19'
        java: 16
        modrinth-id: xss83sOY
        #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
