#
# This file is kept for Folia support.
#

name: 'AdvancedServerList'
author: 'Andre_601'
version: '${plugin.version}'
description: '${plugin.description}'

main: 'ch.andre601.advancedserverlist.paper.PaperCore'

api-version: '1.19'

folia-supported: true

libraries:
  - 'org.spongepowered:configurate-yaml:4.1.2'
  - 'net.kyori:adventure-text-serializer-legacy:4.12.0'
  - 'com.squareup.okhttp3:okhttp:4.10.0'

softdepend:
  - 'PlaceholderAPI'
  - 'Maintenance'

commands:
  advancedserverlist:
    description: 'Main command of AdvancedServerList'
    usage: '/<command> [help|reload|clearCache]'
    aliases:
      - 'asl'
    permission: 'advancedserverlist.admin'

permissions:
  advancedserverlist.*:
    description: 'Grants access to all permissions'
    default: op
    children:
      - 'advancedserverlist.admin'
  advancedserverlist.admin:
    description: 'Grants access to all permissions'
    default: op
    children:
      - 'advancedserverlist.command.*'
  advancedserverlist.command.*:
    description: 'Grants access to all commands'
    default: op
    children:
      - 'advancedserverlist.command.help'
      - 'advancedserverlist.command.reload'
  advancedserverlist.command.help:
    description: 'Grants access to /asl help'
    default: op
  advancedserverlist.command.reload:
    description: 'Grants access to /asl reload'
    default: op
  advancedserverlist.command.clearcache:
    description: 'Clears the Player and Favicon cache'
    default: op